version: '3.8'

services:
  # Banco de Dados - Central de toda a nossa estratégia
  postgres:
    image: postgres:15
    container_name: finance_dw_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=finance_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # API - Onde o "Leão" processa as requisições
  credit-api:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.9
    container_name: source_credit_api
    volumes:
      - ./src/api:/app
    ports:
      - "8000:80"
    depends_on:
      - postgres

volumes:
  postgres_data: